### PR TITLE
Upgrade EMR and centralize metastore

### PR DESCRIPTION
**Pull request by robotblake**

### CODE REVIEW

**Comment by vitillo** [comment]
Please split the patch in individual commits; we are striving to adhere to [this guidelines](http://chris.beams.io/posts/git-commit/) in Telemetry-land.

**Comment by robotblake** [comment]
Updated.

**Comment by vitillo** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

_[README.md, line 6 [r1]](https://reviewable.io:443/reviews/mozilla/emr-bootstrap-presto/5#-KN7JErd0dO6BqsN8h2G:-KN7JEreqOAq3MtfqsMe:-997099653) ([raw file](https://github.com/mozilla/emr-bootstrap-presto/blob/22adb7fb67bb73726354f888df2458496fecf008/README.md#L6)):_

> ``` Markdown
> This packages contains the AWS bootstrap scripts for Mozilla's flavoured Presto setup.
> 
> ## Create Hive Metastore
> ```

Since we are planning to use different environments in the future (i.e. stage/test/prod), I think it would be worthwhile to put these instructions in an ansible script called e.g. `deploy_metastore.yml`.

---

_[README.md, line 35 [r1]](https://reviewable.io:443/reviews/mozilla/emr-bootstrap-presto/5#-KN7KTv_28qqHxzJcaN4:-KN7KTvaS_MkvalGozD0:-1039674275) ([raw file](https://github.com/mozilla/emr-bootstrap-presto/blob/22adb7fb67bb73726354f888df2458496fecf008/README.md#L35)):_

> ``` Markdown
> ```
> 
> After creating this you'll want to modify ansible/files/configuration.json with the credentials you used as well as the correct endpoint of the RDS instance.
> 
> ```
> ```

Ideally there should be no manual step involved.

---

_[ansible/files/telemetry.sh, line 79 [r1]](https://reviewable.io:443/reviews/mozilla/emr-bootstrap-presto/5#-KN7LoLTnt2JWF79t83l:-KN7LoLTnt2JWF79t83m:-925072321) ([raw file](https://github.com/mozilla/emr-bootstrap-presto/blob/22adb7fb67bb73726354f888df2458496fecf008/ansible/files/telemetry.sh#L79)):_

> ``` Shell
> aws s3 sync $TELEMETRY_CONF_BUCKET/packages/hive/\$v .
> tar zxvf apache-hive-\$v-bin.tar.gz
> mv apache-hive-\$v-bin/hcatalog /usr/lib/hive-\$v-hcatalog
> ```

Out of curiosity, how are we using HCatalog?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/emr-bootstrap-presto/5)_

**Comment by vitillo** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

_[a discussion](https://reviewable.io:443/reviews/mozilla/emr-bootstrap-presto/5#-KN7NYsk7nyv43DOez7a:-KN7NYslZ3xqjmkdjgvZ:-1767451493) (no related file):_
Please set the r? flag on the corresponding Bug on Bugzilla for this PR so we can keep track of this.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/emr-bootstrap-presto/5)_

**Pull request closed without merging**
